export const APRODUCT_LIST_REQUEST = 'APRODUCT_LIST_REQUEST';
export const APRODUCT_LIST_SUCCESS = 'APRODUCT_LIST_SUCCESS';
export const APRODUCT_LIST_FAIL = 'APRODUCT_LIST_FAIL';

export const APRODUCT_DETAILS_REQUEST = 'APRODUCT_DETAILS_REQUEST';
export const APRODUCT_DETAILS_SUCCESS = 'APRODUCT_DETAILS_SUCCESS';
export const APRODUCT_DETAILS_FAIL = 'APRODUCT_DETAILS_FAIL';

export const APRODUCT_SAVE_REQUEST = 'APRODUCT_SAVE_REQUEST';
export const APRODUCT_SAVE_SUCCESS = 'APRODUCT_SAVE_SUCCESS';
export const APRODUCT_SAVE_FAIL = 'APRODUCT_SAVE_FAIL';

export const APRODUCT_DELETE_REQUEST = 'APRODUCT_DELETE_REQUEST';
export const APRODUCT_DELETE_SUCCESS = 'APRODUCT_DELETE_SUCCESS';
export const APRODUCT_DELETE_FAIL = 'APRODUCT_DELETE_FAIL';